name: Delete

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: delete all_model    
      run: |
       cd bin/bash
       ls
