name: Delete
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: delete all_model    
      run: |
       git config --global user.name "AutumnCrocus"
       git config --global user.email "t4kicyis@gmail.com"
       git clone https://github.com/AutumnCrocus/shadow_sim.git
       git checkout master
       git pull
       git rm model/*.pth
       git commit
       git push origin master
