name: Delete
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: delete all_model    
      run: |
       git clone https://github.com/AutumnCrocus/shadow_sim.git
       git rm ./model/*pth
       git commit
       git push origin master
