name: Delete
on:
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: delete all_model    
      run: |
       git add "https://github.com/AutumnCrocus/shadow_sim.git"
       git pull master
       git rm ./model/*pth
       git commit
