# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    env:
      MODEL_NAME: Multi_Dual_2020_7_4_23_15_45_31%_cuda.pth
      O_MODEL_NAME: Multi_Dual_2020_6_22_18_25_10_all_cuda.pth
      PLAYER_TYPE: 2
      MODE: mirror
      PLAYER1: 29
      N: 100
      DECK_ID: 5
      DECK_LIST: "0,1,4,5,10,11"  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # 対応するrequirementsファイルにキャッシュヒットがあるかを見る
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pip_lib
      run: |
        pip install -r requirements.txt
    
    - name: Run Test     
      run: |
       python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decklist $DECK_LIST --mode $MODE --model_name $MODEL_NAME
       #python3 multi_test.py --check True --episode_num 100 --model_name $MODEL_NAME --opponent_model_name $O_MODEL_NAME --node_num 100 --deck_list $DECK_LIST

