# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on:
  push:
    paths: ".github/workflows/*.yml"
  workflow_dispatch:

jobs:
  build: 
    env:
      MODEL_NAME: Multi_Dual_2020_10_21_23_23_36_23_256_cuda.pth
      O_MODEL_NAME: Multi_Dual_2020_10_21_23_23_36_23_256_cuda.pth
      PLAYER_TYPES1: "29,2"
      PLAYER_TYPES2: "29,13"
      MODE: mirror
      N: 200
      DECK_LIST: "100"

      NODE_NUM: 100
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # 対応するrequirementsファイルにキャッシュヒットがあるかを見る
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pip_lib
      run: |
        pip install -r requirements.txt
    
    - name: Run Test1     
      run: |
       python3 test.py --N  $N --playertypes $PLAYERTYPES1 --decklist $DECK_LIST --mode $MODE --model_name $MODEL_NAME --node_num $NODE_NUM
    - name: Run Test2     
      run: |
       python3 test.py --N  $N --playertypes $PLAYERTYPES2 --decklist $DECK_LIST --mode $MODE --model_name $MODEL_NAME --node_num $NODE_NUM
       
    #- name: Run Test2     
    #  run: |
    #   python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 2 --decklist $DECK_LIST --mode $MODE --model_name $MODEL_NAME --node_num $NODE_NUM
        
       
