# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MODEL_NAME: Multi_Dual_2020_5_17_16_23_16_all_100nodes.pth
      PLAYER_TYPE: 2
      MODE: background_demo
      PLAYER1: 29
      N: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # 対応するrequirementsファイルにキャッシュヒットがあるかを見る
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pip_lib
      run: |
        pip install -r requirements.txt
    - name: Run Test0
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 0  --decktype2 0 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test1
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 1  --decktype2 1 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test2
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 2  --decktype2 2 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test3
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 3  --decktype2 3 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test4
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 4  --decktype2 4 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test5
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 5  --decktype2 5 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test6
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 6  --decktype2 6 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test7
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 7  --decktype2 7 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test8
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 8  --decktype2 8 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test9
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 9  --decktype2 9 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test10
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 10  --decktype2 10 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test11
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 11 --decktype2 11 --mode $MODE --model_name $MODEL_NAME1
    - name: Run Test12
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 12 --decktype2 12 --mode $MODE --model_name $MODEL_NAME
    - name: Run Test13
      run: |
        python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 13  --decktype2 13 --mode $MODE --model_name $MODEL_NAME
