# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # 対応するrequirementsファイルにキャッシュヒットがあるかを見る
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pip_lib
      run: |
        pip install -r requirements.txt
    - name: Run Test1
      run: |
        python3 test.py --N 100 --playertype1 1 --playertype2 1 --decktype1 10 --decktype2 10 --mode background_demo 
    - name: Run Test2
      run: |
        python3 test.py --N 10 --playertype1 29 --playertype2 29 --decktype1 0 --decktype2 0 --mode background_demo  --model_name Multi_Dual_2020_3_24_15_51_31_75%.pth
    
    - name: Run Test3
      run: |
        python3 test.py --N 10 --playertype1 29 --playertype2 29 --decktype1 2 --decktype2 2 --mode background_demo  --model_name Multi_Dual_2020_3_24_15_51_31_75%.pth
        
    - name: Run Test4
      run: |
        python3 test.py --N 10 --playertype1 29 --playertype2 29 --decktype1 10 --decktype2 10 --mode background_demo  --model_name Multi_Dual_2020_3_24_15_51_31_75%.pth
