# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MODEL_NAME: Multi_Dual_2020_5_21_16_40_20_all_100nodes.pth
      PLAYER_TYPE: 2
      MODE: background_demo
      PLAYER1: 29
      N: 40
      DECK_ID: "{{item}}"
      -loop:
        1
        2
        3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # 対応するrequirementsファイルにキャッシュヒットがあるかを見る
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pip_lib
      run: |
        pip install -r requirements.txt
    - name: Run Test
      run: | 
       python3 test.py --N  $N --playertype1 $PLAYER1 --playertype2 $PLAYER_TYPE --decktype1 11 --decktype2 11 --mode $MODE --model_name $MODEL_NAME
