# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      MODEL_NAME: Multi_Dual_2020_4_11_15_25_34_19%.pth
      PLAYER_TYPE: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # 対応するrequirementsファイルにキャッシュヒットがあるかを見る
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pip_lib
      run: |
        pip install -r requirements.txt

    - name: Run Test0
      run: |
        python3 test.py --N  20 --playertype1 29 --playertype2 $PLAYER_TYPE --decklist "0" --mode mirror --model_name $MODEL_NAME
    - name: Run Test1
      run: |
        python3 test.py --N  20 --playertype1 29 --playertype2 $PLAYER_TYPE --decklist "1" --mode mirror --model_name $MODEL_NAME
    - name: Run Test4
      run: |
        python3 test.py --N  20 --playertype1 29 --playertype2 $PLAYER_TYPE --decklist "4" --mode mirror --model_name $MODEL_NAME
    - name: Run Test5
      run: |
        python3 test.py --N  20 --playertype1 29 --playertype2 $PLAYER_TYPE --decklist "5" --mode mirror --model_name $MODEL_NAME
    - name: Run Test10
      run: |
        python3 test.py --N  20 --playertype1 29 --playertype2 $PLAYER_TYPE --decklist "10" --mode mirror --model_name $MODEL_NAME
    - name: Run Test13
      run: |
        python3 test.py --N  20 --playertype1 29 --playertype2 $PLAYER_TYPE --decklist "13" --mode mirror --model_name $MODEL_NAME

